using System;
using System.Collections.Generic;
using System.Data.OleDb;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace CTOTracker.View.UserControls
{
    /// <summary>
    /// Interaction logic for RoleTaskView.xaml
    /// </summary>
    public partial class RoleTaskView : UserControl
    {
        private DataConnection dataConnection;

        public RoleTaskView()
        {
            InitializeComponent();
            dataConnection = new DataConnection();
            LoadRoleView();
        }

        private void LoadRoleView()
        {
            using (OleDbConnection connection = dataConnection.GetConnection())
            {
                try
                {
                    connection.Open();
                    string query = "SELECT roleName FROM Role";   // Specify the columns you want to retrieve
                    OleDbDataAdapter adapter = new OleDbDataAdapter(query, connection);
                    DataTable dataTable = new DataTable();          // Retrieve data from the database
                    adapter.Fill(dataTable);

         
                    roleDataGrid.ItemsSource = dataTable.DefaultView;     // Bind the DataTable to the DataGridView
                    
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error: " + ex.Message, "Error");
                }
                finally
                {
                    connection.Close();
                }
            }
        }
        private void roleSave_Click(object sender, RoutedEventArgs e)
        {

        }

        private void roleDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

            roleDataGrid.Columns[0].Header = "Role";
        }
    }
}
